import { useEffect, useState } from 'react';
import { ArrowRight, BadgeCheck, ChevronLeft, ChevronRight, CircleUserRound, FileText,
  Landmark, MapPin, Search, ShieldCheck, Users, Wallet, X } from 'lucide-react';
import { api, money, type Employee, type Line, type Page, type Role } from './api';
import { Heading, PanelTitle, Pill } from './ui';

export default function PeoplePage({role,compensation,onRefresh,setError,setToast}:{role:Role;compensation:boolean;onRefresh:()=>Promise<void>;setError:(x:string)=>void;setToast:(x:string)=>void}){
  const [items,setItems]=useState<Page<Employee>>({items:[],total:0,page:1,size:20});
  const [search,setSearch]=useState('');
  const [page,setPage]=useState(1);
  const [selected,setSelected]=useState<Employee|null>(null);
  const [bankLast4,setBankLast4]=useState('');
  const [taxRegime,setTaxRegime]=useState<'new'|'old'>('new');
  const [payslip,setPayslip]=useState<{period:string;status:string;line:Line}|null>(null);
  const [loading,setLoading]=useState(false);
  useEffect(()=>{
    if(role==='employee'){
      api<Employee>('/employees/EMP00001',role).then(employee=>setItems({items:[employee],total:1,page:1,size:20})).catch(err=>setError(err.message));
    }else{
      api<Page<Employee>>(`/employees?page=${page}&size=20&search=${encodeURIComponent(search)}`,role).then(setItems).catch(err=>setError(err.message));
    }
  },[role,page,search,setError]);
  function openEmployee(employee:Employee){setSelected(employee);setBankLast4(employee.bankAccountLast4 ?? '');setTaxRegime(employee.taxRegime);}
  async function save(){if(!selected)return;setLoading(true);try{
    await api(`/employees/${selected.id}`,role,{method:'PATCH',body:JSON.stringify({bankReady:/^\d{4}$/.test(bankLast4),bankAccountLast4:bankLast4,taxRegime})});
    setToast('Employee record saved. Recalculate the run to apply changes.');
    const updated=await api<Employee>(`/employees/${selected.id}`,role);setSelected(updated);
    await onRefresh();
  }catch(err){setError((err as Error).message);}finally{setLoading(false);}}
  async function viewPayslip(employee:Employee){try{setPayslip(await api(`/runs/RUN-2026-09/payslip/${employee.id}`,role));}catch(err){setError((err as Error).message);}}
  const title=compensation?'Compensation':'People';
  return <>
    <Heading eyebrow={compensation?'COMPENSATION / SALARY STRUCTURES':'PEOPLE / EMPLOYEE RECORDS'} title={title} description={role==='employee'?'Your employment and pay information.':`${items.total.toLocaleString('en-IN')} employee records across five Indian branches.`}/>
    <div className="people-layout"><section className="panel people-list"><PanelTitle title={compensation?'Salary structures':'Employee directory'} description={compensation?'Select an employee to inspect monthly pay components.':'Search and inspect employee records.'}/>
      {role!=='employee'&&<div className="filter-row"><div className="table-search"><Search size={17}/><input placeholder="Find employee by name or ID" value={search} onChange={event=>{setSearch(event.target.value);setPage(1);}}/></div><span className="result-count">{items.total.toLocaleString('en-IN')} employees</span></div>}
      <div className="table-scroll"><table><thead><tr><th>Employee</th><th>Branch</th><th>Pay group</th><th>{compensation?'Monthly gross':'Tax regime'}</th><th>Bank</th><th/></tr></thead><tbody>{items.items.map(employee=><tr key={employee.id} onClick={()=>openEmployee(employee)}><td><div className="employee-cell"><span className="mini-avatar">{employee.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</span><span><strong>{employee.name}</strong><small>{employee.id}</small></span></div></td><td>{employee.branch}<small>{employee.state}</small></td><td>{employee.payGroup}</td><td>{compensation?money(employee.monthlyBasic+employee.monthlyHra+employee.monthlySpecial):<Pill tone="info">{employee.taxRegime} regime</Pill>}</td><td>{employee.bankReady?<Pill tone="success">Verified</Pill>:<Pill tone="danger">Missing</Pill>}</td><td><ChevronRight size={17}/></td></tr>)}</tbody></table></div>
      {role!=='employee'&&<div className="pagination"><span>Showing {(page-1)*items.size+1}–{Math.min(page*items.size,items.total)} of {items.total.toLocaleString('en-IN')}</span><div><button disabled={page<=1} onClick={()=>setPage(page-1)}><ChevronLeft size={16}/></button><span>Page {page}</span><button disabled={page*items.size>=items.total} onClick={()=>setPage(page+1)}><ChevronRight size={16}/></button></div></div>}
    </section><aside className="panel people-side"><div className="side-illustration"><Users size={34}/></div><h2>One trusted employee record</h2><p>Employment location, pay structure, tax choice and statutory eligibility feed every payroll calculation.</p><div className="side-benefit"><BadgeCheck size={18}/> Effective-dated pay details</div><div className="side-benefit"><ShieldCheck size={18}/> Role-controlled changes</div><div className="side-benefit"><FileText size={18}/> Explainable payslips</div></aside></div>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><aside className="drawer" onClick={event=>event.stopPropagation()}><div className="drawer-header"><div><small>EMPLOYEE RECORD</small><h2>{selected.name}</h2><span>{selected.id} · {selected.payGroup}</span></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="drawer-body"><div className="employee-summary"><span className="large-avatar"><CircleUserRound size={36}/></span><div><strong>{selected.name}</strong><span><MapPin size={14}/> {selected.branch}, {selected.state}</span></div></div><h3>Monthly salary</h3><div className="detail-row"><span>Basic pay</span><strong>{money(selected.monthlyBasic)}</strong></div><div className="detail-row"><span>House rent allowance</span><strong>{money(selected.monthlyHra)}</strong></div><div className="detail-row"><span>Special allowance</span><strong>{money(selected.monthlySpecial)}</strong></div><div className="detail-row total"><span>Regular gross</span><strong>{money(selected.monthlyBasic+selected.monthlyHra+selected.monthlySpecial)}</strong></div><h3>Statutory setup</h3><div className="detail-row"><span>EPF membership</span><strong>{selected.pfMember?'Yes':'No'}</strong></div><div className="detail-row"><span>ESI membership</span><strong>{selected.esiMember?'Yes':'No'}</strong></div><div className="detail-row"><span>EPS membership</span><strong>{selected.epsMember?'Yes':'No'}</strong></div><div className="detail-row"><span>Professional tax & LWF</span><strong>{selected.state} rules</strong></div><h3>Tax & payment</h3><label className="form-label">Tax regime<select value={taxRegime} onChange={event=>setTaxRegime(event.target.value as 'new'|'old')} disabled={role==='employee'||role==='auditor'||role==='finance-approver'||role==='payroll-operator'}><option value="new">New (default)</option><option value="old">Old</option></select></label><label className="form-label">Bank account ending<input value={bankLast4} maxLength={4} placeholder="Last four digits" onChange={event=>setBankLast4(event.target.value)} disabled={role==='employee'||role==='auditor'||role==='finance-approver'||role==='payroll-operator'}/></label><div className="detail-row"><span>Bank status</span><Pill tone={selected.bankReady?'success':'danger'}>{selected.bankReady?'Verified':'Missing'}</Pill></div><div className="drawer-actions">{['admin','hr-operator'].includes(role)&&<button className="button primary" disabled={loading} onClick={save}>{loading?'Saving…':'Save record'} <ArrowRight size={16}/></button>}<button className="button outline" onClick={()=>viewPayslip(selected)}><FileText size={16}/> View payslip</button></div><div className="info-strip"><Landmark size={17}/> This demo stores only fictional bank ending digits. Production bank verification and encryption are pending.</div></div></aside></div>}
    {payslip&&<div className="overlay modal-overlay" onClick={()=>setPayslip(null)}><div className="modal payslip-modal" onClick={event=>event.stopPropagation()}><button className="icon-button modal-close" onClick={()=>setPayslip(null)}><X size={20}/></button><div className="payslip-header"><div><span>ASTER GROUP</span><h2>Payslip · September 2026</h2><small>Synthetic demonstration document</small></div><Wallet size={31}/></div><div className="payslip-net"><span>Net pay</span><strong>{money(payslip.line.net)}</strong><small>{payslip.line.employeeName} · {payslip.line.employeeId}</small></div><div className="payslip-columns"><div><h3>Earnings</h3>{[['Basic',payslip.line.basic],['HRA',payslip.line.hra],['Special',payslip.line.special],['Variable',payslip.line.variablePay]].map(([key,value])=><div className="detail-row" key={String(key)}><span>{key}</span><strong>{money(Number(value))}</strong></div>)}<div className="detail-row total"><span>Gross</span><strong>{money(payslip.line.gross)}</strong></div></div><div><h3>Deductions</h3>{[['PF',payslip.line.pfEmployee],['ESI',payslip.line.esiEmployee],['Professional tax',payslip.line.professionalTax],['Labour welfare',payslip.line.labourWelfareFund],['Income tax',payslip.line.incomeTax],['Other',payslip.line.otherDeduction]].map(([key,value])=><div className="detail-row" key={String(key)}><span>{key}</span><strong>{money(Number(value))}</strong></div>)}<div className="detail-row total"><span>Total</span><strong>{money(payslip.line.deductions)}</strong></div></div></div><div className="modal-actions"><button className="button outline" onClick={()=>setPayslip(null)}>Close</button><button className="button primary" onClick={()=>window.print()}>Print payslip</button></div></div></div>}
  </>;
}
